remote_theme: sylhare/Type-on-Strap
title: Ambiente Brasil Oficial
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/ambiente-brasil-oficial"
author: Redação Ambiente Brasil Oficial
email: contato@ambiente-brasil-oficial.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
